apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.uuid }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.uuid }}
    spec:
      containers:
        - image: {{ .Values.repo }}/{{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}-pod
          env:
            - name: DB_HOST
              value: {{ .Values.dbhost }}
            - name: DB_TYPE
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-{{ .Values.uuid }}
                  key: SQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-{{ .Values.uuid }}
                  key: SQL_PASSWORD
            - name: SITENAME
              value: {{ .Values.url }}
            - name: DB_NAME
              value: {{ .Values.dbname }}
          ports:
            - containerPort: 3000
              name: wiki
          resources:
            requests:
              cpu: 100m
          livenessProbe:
           httpGet:
             path: /
             port: 3000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 180
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /
             port: 3000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 180
           periodSeconds: 3
