apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  labels:
    app: {{ .Values.name }}-wiki-pod
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}-{{ .Values.uuid }}
