replicaCount: 1

uuid: hbdftsrfed
name: mautic
image: mautic/mautic:v4
url: mautic.server.robots.beer
version: 1

dbhost: mysql
dbuser: mautic
dbpass: mautic
dbname: mautic

mauticuser: adminuser
mauticpass: "testAdminPassword3322!"
adminEmail: matte@elino.se
adminFirstName: firstname
adminLastName: lastname
forceInstall: "true"

resource: low
#Only for custom
cpu: 100m
memory: 128Mi

storage: 10Gi
storageClass: standard

hosting:
  tags: 
    host/deployname: mautic
    host/resources: low
    host/deploydate: date
    host/userid: userid
    host/id: idss
  id:
    - 1111-2222-3333-4444
  repo: github.com/hackingrobots/helmrepo/mautic