apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.uuid }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.uuid }} 
    spec:
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}
          env:
            - name: MATOMO_DATABASE_HOST
              value: {{ .Values.dbhost }}
            - name: MATOMO_DATABASE_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: {{ .Values.name }}-{{ .Values.uuid }}
                   key: SQL_USER
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: {{ .Values.name }}-{{ .Values.uuid }}
                   key: SQL_PASSWORD
            - name: MATOMO_DATABASE_DBNAME
              value: {{ .Values.dbname }}
            - name: SITENAME
              value: {{ .Values.url }}
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
          #livenessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
          #readinessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  labels:
    app: {{ .Values.name }}-{{ .Values.uuid }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }} 
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.name }}-{{ .Values.uuid }}