apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  labels:
    app: {{ .Values.name }}-{{ .Values.uuid }}
    {{- toYaml .Values.hosting.tags | nindent 4 }}
  annotations:
    {{- toYaml .Values.hosting.tags | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.uuid }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.uuid }}
        {{- toYaml .Values.hosting.tags | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
        - args:
          - --nginx.scrape-uri=http://127.0.0.1:80/basic_status
          image: nginx/nginx-prometheus-exporter
          imagePullPolicy: Always
          name: metrics
          ports:
          - containerPort: 9113
            name: metrics
            protocol: TCP
        - name: {{ .Values.name }}
          image: "{{ .Values.image }}"
          env:
            - name: MOODLE_DB_HOST
              value: {{ .Values.name }}-{{ .Values.uuid }}-mysql-master
            - name: MOODLE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-{{ .Values.uuid }}
                  key: SQL_USER
            - name: MOODLE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-{{ .Values.uuid }}
                  key: SQL_PASSWORD
            - name: MOODLE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-{{ .Values.uuid }}
                  key: SQL_USER
          ports:
            - containerPort: 80
          resources:          
          {{ if eq .Values.resource "low" }}
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          {{ else if eq .Values.resource "medium" }}
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          {{ else if eq .Values.resource "high" }}
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          {{ else if eq .Values.resource "custom" }}
            requests:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
          {{ end }}
          volumeMounts:
            - name: moodle-persistent-storage
              mountPath: /var/www/html/shared
      volumes:
        - name: moodle-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-{{ .Values.uuid }}