apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.uuid }} 
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.uuid }} 
    spec:
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}
          env:
            - name: MAUTIC_DB_HOST
              value: '{{ .Values.dbhost}}'
            - name: MAUTIC_DB_USER
              valueFrom:
                 secretKeyRef:
                   name: {{ .Values.name }}-{{ .Values.uuid }}
                   key: SQL_USER
            - name: MAUTIC_DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: {{ .Values.name }}-{{ .Values.uuid }}
                   key: SQL_PASSWORD
            - name: MAUTIC_DB_NAME
              value: {{ .Values.dbname }}
            - name: MAUTIC_RUN_CRON_JOBS
              value: 'true'
            - name: SITENAME
              value: '{{ .Values.url }}'
            - name: MAUTIC_TRUSTED_PROXIES
              value: '["0.0.0.0/0"]'
            - name: MAUTIC_URL
              value: https://{{ .Values.url }}
            - name: MAUTIC_ADMIN_EMAIL
              value: {{ .Values.adminEmail }}
            - name: MAUTIC_ADMIN_PASSWORD
              value: {{ .Values.mauticpass | quote }}
            - name: MAUTIC_ADMIN_USERNAME
              value: {{ .Values.mauticuser }}
            - name: MAUTIC_ADMIN_FIRSTNAME
              value: {{ .Values.adminFirstName }}
            - name: MAUTIC_ADMIN_LASTNAME
              value: {{ .Values.adminLastName }}
            - name: MAUTIC_INSTALL_FORCE
              value: {{ .Values.forceInstall | quote }}
          ports:
            - containerPort: 80
              name: http
          resources:
          {{ if eq .Values.resource "low" }}
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          {{ else if eq .Values.resource "medium" }}
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          {{ else if eq .Values.resource "high" }}
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          {{ else if eq .Values.resource "custom" }}
            requests:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
          {{ end }}
          #livenessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
          #readinessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
