replicaCount: 1

uuid: hbdftsrfed
name: matomo
image: matomo
url: matomo-test.server.robots.beer



dbhost: mysql
dbuser: matomo
dbpass: password
dbname: matomo

hosting:
  tags:
    host/deployname: matomo
    host/resources: low
    host/deploydate: date
    host/userid: userid
    host/id: idss